name: to_lendo_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  packages:
    path: ./packages

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#6B3EFF"
  adaptive_icon_foreground_inset: 18

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animations/
    - assets/images/
