name: packages
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  freezed_annotation: ^2.4.4
  get_it: ^9.2.0
  go_router: ^17.0.1
  hugeicons: ^1.1.4
  lottie: ^3.3.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
