name: packages
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.0
  supabase_flutter: ^2.12.0
  fpdart: ^1.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  hugeicons: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
